Fix

diff --git a/.github/workflows/validate_task_images.yml b/.github/workflows/validate_task_images.yml
--- a/.github/workflows/validate_task_images.yml
+++ b/.github/workflows/validate_task_images.yml
@@ -117,12 +117,19 @@ jobs:
           # Run the container and execute the evaluator
           # The evaluator would almost always say 0 marks granted, but that's
           # fine, we only run it to make sure it at least compiles
-          docker run --name $CONTAINER_NAME -d $IMAGE_NAME
-          docker exec $CONTAINER_NAME python_default /utils/evaluator.py
+          docker run --name $CONTAINER_NAME $IMAGE_NAME python /utils/evaluator.py
+          
+          # Capture the exit code
+          EXIT_CODE=$?
           
           # Clean up
-          docker stop $CONTAINER_NAME
           docker rm $CONTAINER_NAME
+          
+          # If the evaluator failed, exit the workflow
+          if [ $EXIT_CODE -ne 0 ]; then
+            echo "Evaluator failed in $task_dir"
+            exit $EXIT_CODE
+          fi
           
           cd -
         done
